---

- name: Install firewalld
  yum:
    name: firewalld
    state: present

- name: Allow Network Ports in Firewalld
  firewalld:
   port: "{{ item }}"
   state: enabled
   permanent: yes
   immediate: yes
  with_items: "{{ master_ports if ('kubernetes_master_nodes' in group_names) else worker_ports }}"

- name: Enabling Bridge Firewall Rule
  shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"