---

- name: Creating a repository file for Kubernetes
  file:
    path: /etc/yum.repos.d/kubernetes.repo
    state: touch

- name: Adding repository details in Kubernetes repo file.
  blockinfile:
   path: /etc/yum.repos.d/kubernetes.repo
   block: |
    [kubernetes]
    name=Kubernetes
    baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled=1
    gpgcheck=1
    repo_gpgcheck=1
    gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
      https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Check for containerd
  shell: containerd -v && echo installed || echo missing
  register: containerd_status

- name: Install containerd
  shell: |
   yum install -y yum-utils device-mapper-persistent-data lvm2
   yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
   yum update -y && sudo yum install -y containerd.io
   mkdir -p /etc/containerd
   containerd config default | sudo tee /etc/containerd/config.toml
   systemctl restart containerd
  when: containerd_status.stdout == 'missing'

- name: Installing required packages
  yum:
   name: "{{ packages }}"
   state: present

- name: Starting and Enabling the required services
  service:
   name: "{{ item }}"
   state: started
   enabled: yes
  with_items: "{{ services }}"